# Generated by Django 5.2.1 on 2026-02-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.CharField(blank=True, max_length=120)),
                ('power', models.CharField(blank=True, max_length=120)),
                ('dimensions', models.CharField(blank=True, max_length=140)),
                ('warranty', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='machines/')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
