# Generated by Django 5.2.11 on 2026-02-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='GIFT Excellence', max_length=120)),
                ('site_tagline', models.CharField(blank=True, max_length=200)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Somente números com DDI. Ex: 5531999999999', max_length=30)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('address_text', models.CharField(blank=True, max_length=220)),
                ('google_maps_embed_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configurações do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
    ]
