# Generated by Django 5.2.1 on 2026-02-26 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('CORTE', 'Corte'), ('PRENSA', 'Prensa'), ('BATER_FUMO', 'Bater fumo'), ('ELETRICA', 'Elétrica'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CORTE', 'Corte'), ('PRENSA', 'Prensa'), ('BATER_FUMO', 'Bater fumo'), ('ELETRICA', 'Elétrica'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='assistencia_app.machinemodel')),
            ],
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('file', models.FileField(blank=True, null=True, upload_to='manuals/')),
                ('url', models.URLField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuals', to='assistencia_app.machinemodel')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('compatible_models', models.ManyToManyField(blank=True, related_name='compatible_parts', to='assistencia_app.machinemodel')),
            ],
        ),
        migrations.CreateModel(
            name='PartRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('ANALYSIS', 'Em análise'), ('QUOTED', 'Orçado'), ('SENT', 'Enviado'), ('CANCELED', 'Cancelado')], default='OPEN', max_length=12)),
                ('contact_name', models.CharField(max_length=120)),
                ('contact_phone', models.CharField(max_length=40)),
                ('shipping_name', models.CharField(max_length=120)),
                ('shipping_cpf_cnpj', models.CharField(blank=True, max_length=40)),
                ('shipping_zip', models.CharField(max_length=20)),
                ('shipping_address', models.CharField(max_length=160)),
                ('shipping_number', models.CharField(blank=True, max_length=20)),
                ('shipping_complement', models.CharField(blank=True, max_length=80)),
                ('shipping_neighborhood', models.CharField(blank=True, max_length=80)),
                ('shipping_city', models.CharField(max_length=80)),
                ('shipping_uf', models.CharField(max_length=2)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_requests', to='assistencia_app.machine')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('notes', models.CharField(blank=True, max_length=160)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assistencia_app.part')),
                ('part_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assistencia_app.partrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CORTE', 'Corte'), ('PRENSA', 'Prensa'), ('BATER_FUMO', 'Bater fumo'), ('ELETRICA', 'Elétrica'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('TRIAGE', 'Em triagem'), ('WAITING', 'Aguardando cliente'), ('QUOTE', 'Orçamento'), ('SENT', 'Enviado'), ('DONE', 'Finalizado'), ('CANCELED', 'Cancelado')], default='OPEN', max_length=12)),
                ('priority', models.CharField(choices=[('LOW', 'Baixa'), ('MEDIUM', 'Média'), ('HIGH', 'Alta')], default='MEDIUM', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='assistencia_app.machine')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                ('symptom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='assistencia_app.symptom')),
            ],
        ),
        migrations.CreateModel(
            name='TicketMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tickets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='assistencia_app.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(choices=[('CLIENT', 'Cliente'), ('ADMIN', 'Empresa')], default='CLIENT', max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistencia_app.ticket')),
            ],
        ),
    ]
