# Generated by Django 5.2.11 on 2026-02-26 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencia_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['-id'], 'verbose_name': 'Máquina', 'verbose_name_plural': 'Máquinas'},
        ),
        migrations.AlterModelOptions(
            name='machinemodel',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Modelo de Máquina', 'verbose_name_plural': 'Modelos de Máquina'},
        ),
        migrations.AlterModelOptions(
            name='manual',
            options={'ordering': ['model__name', 'title'], 'verbose_name': 'Manual', 'verbose_name_plural': 'Manuais'},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['sku'], 'verbose_name': 'Peça', 'verbose_name_plural': 'Peças'},
        ),
        migrations.AlterModelOptions(
            name='partrequest',
            options={'ordering': ['-id'], 'verbose_name': 'Solicitação de Peça', 'verbose_name_plural': 'Solicitações de Peça'},
        ),
        migrations.AlterModelOptions(
            name='partrequestitem',
            options={'ordering': ['id'], 'verbose_name': 'Item da Solicitação', 'verbose_name_plural': 'Itens da Solicitação'},
        ),
        migrations.AlterModelOptions(
            name='symptom',
            options={'ordering': ['category', 'title'], 'verbose_name': 'Sintoma', 'verbose_name_plural': 'Sintomas'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-id'], 'verbose_name': 'Chamado', 'verbose_name_plural': 'Chamados'},
        ),
        migrations.AlterModelOptions(
            name='ticketmedia',
            options={'ordering': ['-id'], 'verbose_name': 'Mídia do Chamado', 'verbose_name_plural': 'Mídias do Chamado'},
        ),
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Mensagem do Chamado', 'verbose_name_plural': 'Mensagens do Chamado'},
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['owner', 'model'], name='assistencia_owner_i_5f363e_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['serial'], name='assistencia_serial_382a6c_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['sku'], name='assistencia_sku_68fc16_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['name'], name='assistencia_name_36be76_idx'),
        ),
        migrations.AddIndex(
            model_name='partrequest',
            index=models.Index(fields=['owner', 'status'], name='assistencia_owner_i_35afd1_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['owner', 'status'], name='assistencia_owner_i_4b2428_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['machine', 'status'], name='assistencia_machine_870383_idx'),
        ),
    ]
